# Generated by Django 3.2.8 on 2022-10-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_paciente', models.TextField(max_length=12, verbose_name='Rut')),
                ('nombre_completo', models.TextField(max_length=100, verbose_name='Nombre')),
                ('telefono', models.IntegerField(max_length=9, verbose_name='Teléfono')),
                ('nacionalidad', models.TextField(max_length=80, verbose_name='Nacionalidad')),
                ('direccion', models.TextField(max_length=300, verbose_name='Dirección')),
                ('email', models.TextField(max_length=150, verbose_name='Email')),
                ('contrasenia', models.TextField(max_length=150, verbose_name='Contrasenia')),
            ],
        ),
    ]
