# Generated by Django 3.2.8 on 2022-10-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(verbose_name='Teléfono'),
        ),
    ]
