# Generated by Django 3.2.8 on 2022-10-13 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_alter_usuario_telefono'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuario',
            new_name='paciente',
        ),
    ]
